### ISSUE TITLE
Denzanali Trial of Posession mission does not auto-complete

### ISSUE THREAD

**Issue by Thom293** [AaronGullickson/mekhq#39]
Title.  It remained open on both the Briefing Room tab and in the objectives tab, even though successfully completed.

If it matters I bid a binary but did not engage in the 1 on 1 duels option.

Screens below show it still active in both places, and I am already on Twycross.

![image](https://github.com/AaronGullickson/mekhq/assets/23645569/e5c8bcf3-0f90-4747-8d1a-bffe584d3731)

![image](https://github.com/AaronGullickson/mekhq/assets/23645569/3cbcd1d4-3543-4fe5-88ee-72f1c58786d2)

**Comment by Thom293** [comment]
I reloaded Autosave and tried to manually complete it a few days out of Twycross, but it still remained in the Objectives window.

![image](https://github.com/AaronGullickson/mekhq/assets/23645569/db0f1e95-9a7b-4a6a-8e8b-f12fe09b5398)

**Comment by AaronGullickson** [comment]
It looks like it did not stop the story arcs from processing as you went on to Twycross. Thats interesting.

**Comment by Thom293** [comment]
It may not matter, but just in case:  one of the belligerants in the Mess hall scene died in the fighting just before this.  I left them dead to see if would trigger anything.  Dont know if there was supposed to be any follow-up to that story here, but mention it just in case.

**Comment by AaronGullickson** [comment]
Found the issue. The Complete mission story trigger is pointing to the wrong mission. So it advanced properly but does not complete the mission. Correcting the UUID pointer will fix it. I will do that later.

**Comment by AaronGullickson** [comment]
Fixed in eaffa201fe.
