### ISSUE TITLE
Defend Ulric Map is Broken (a MHQ Bug)

### ISSUE THREAD

**Issue by Thom293** [AaronGullickson/mekhq#40]
There is currently a bug with MHQ where Fixed maps dont always stick and it will put you on a random mapsheet.  That happens here.  

The MHQ Bug I reported:  https://github.com/MegaMek/mekhq/issues/3776

Until that bug is fixed, there are some new StratCon map presets that might work.  BaseHot, BaseCold, etc.  Or you could make a denser variation of those.  I THINK fortress city or Residential might work too, but I havent tested if they will get overwritten also.

This is what it put me on instead of Ancient City:
  
![Screenshot (130)](https://github.com/AaronGullickson/mekhq/assets/23645569/7f58ec67-fdab-4fa5-9de3-3f5773a9508d)

**Comment by Thom293** [comment]
Part II of Ulric also had a bad map.

Oddly, the final fixed map worked just fine.

Perhaps its a problem with some of the maps themselves?  Dunno.  Just another datapoint.

**Comment by AaronGullickson** [comment]
It could be a problem with the map specification. I will have a look.

**Comment by AaronGullickson** [comment]
Figured out the issue. The name of the map directory in MekHQ is `deadborder, but in MegaMek its `Deadborder`. When we package up releases, we use MegaMek's boards. The consequence is that this works right when I run from source to test, but not in the releases.

Easy fix is to capitalize it in MekHQ to match MM, but I should also check other folders in this directory while I am at it.

**Comment by Thom293** [comment]
Sweet!  Thanks for fixing.

**Comment by AaronGullickson** [comment]
The PR is merged. Closing.
