### ISSUE TITLE
a Khan's greeting typo

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#44]
### Environment
0.49.49-snapshot
java 11
win 11

### Description
a Khans greeting
there is a typo in the last sentence, there is an extra r in the first geneparents'

" Do you have a problem serving under a Khan older than your gene_r_parents' geneparents and tainted by the Inner Sphere?"

**Comment by AaronGullickson** [comment]
Fixed in 9195bd9834.
