### ISSUE TITLE
AI opponent getting random units that should not be available during 3057

### ISSUE THREAD

**Issue by Jagatai** [AaronGullickson/mekhq#47]
### Environment
What version of MekHQ does your issue apply to?
0.49.19-SNAPSHOT

What operating system are you using?  Windows, Mac, or Linux?
Windows

What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file.
Eclipse Adoptium 11.0.22

### Description
I started the scenario "Hide and seek" in the "Baker 3" mission. One of the first units i saw of the Jade Falcon opponent was a Vulture D with 2*ATM12 when ATMs shouldn't be available until 3060 according to sarna.net (https://www.sarna.net/wiki/Advanced_Tactical_Missile)

### Files
I forgot to save the salvage file, but in this screenshot you can see that i have a mothballed Vulture D that i didn't GM into the game.
![grafik](https://github.com/AaronGullickson/mekhq/assets/20794772/00dc2b56-ee59-46db-9a63-348573e79ef3)

**Comment by AaronGullickson** [comment]
Actually, that's a curated unit not random, so the fault is all mine. I will leave this up for the moment in case there are similar issues in other scenarios.

**Comment by AaronGullickson** [comment]
I checked on that one and it ays 3054 in MM but 3059 in the MUL. I was using MM to figure out timing which explains the discrepancy. So, I will just make the vulture some other config and call it good.

**Comment by AaronGullickson** [comment]
Fixed in b49bae5fdf
