### ISSUE TITLE
NPE mission 1 after action report

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#54]
### Environment
story arcs 0.3
java 11
win 11

### Description
upon complete the 1st mission, completed the after action report and got an NPE error.  error did not crash either MM or MHQ and was able to continue play.

### Files
[megamek.log](https://github.com/AaronGullickson/mekhq/files/14891076/megamek.log)
[mekhq.log](https://github.com/AaronGullickson/mekhq/files/14891077/mekhq.log)
[Young Wolves30570924.cpnx.gz](https://github.com/AaronGullickson/mekhq/files/14891075/Young.Wolves30570924.cpnx.gz)

**Comment by AaronGullickson** [comment]
@bczretribution Have you seen this repeated? I have not been able to reproduce and I am wondering if it was maybe unrelated to story arcs.

**Comment by bczretribution** [comment]
No reproduction so far, was assuming your update fixed it.  I am only on mission 4 though at the moment.  I can open open a new ticket if it rears it's head again.

**Comment by AaronGullickson** [comment]
OK, I will close for now.
