### ISSUE TITLE
scenario failed to generate?

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#56]
### Environment
story arcs v0.3

### Description
arrived at baker 3 and only the diversion scenario generates.  the ambush scenario is absent.  unsure what additional files might be needed, let me know and i will submit.

### Files
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/b9b03f06-2eeb-42f9-9645-bb41e3b17818)

**Comment by AaronGullickson** [comment]
The second scenario generates after first scenario completes because it depends on the outcome.
