### ISSUE TITLE
victory conditions mismatch

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#63]
### Environment
story arcs 0.3

### Description
Into the storm mission.  See images, briefed 70% but actual is 60%

### Files
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/aaaa9dbf-8bc0-49c7-93a7-637facbc0da8)
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/bd34a9e1-357f-456e-88f7-299c6f53fac4)
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/83d78489-2219-44e7-b10d-35b65a70745a)

**Comment by AaronGullickson** [comment]
Resolved by 83dadf49aa
