### ISSUE TITLE
Character Generation: any special ability that has a dropdown does not incur a deduction from your pool of available character generation xp. 

### ISSUE THREAD

**Issue by sldfgunslinger2766** [AaronGullickson/mekhq#66]
Build Date: 2024-04-04T20:05:33.009448
	Today: 2024-04-14
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.20
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

During the initial character set up in the Young Wolves Story Arc, when choosing an SPA that has a dropdown, selecting an option does not deduct xp from the pool available. If a selection is made and then an SPA option with a checkbox is enabled and then disabled, the xp count decrements accordingly. Posting issue at Taharqa's request after raising the issue in the Story Arcs Channel of the Megamek Discord on 4/13/24.

**Comment by AaronGullickson** [comment]
This requires adding a listener in megamek to listen for changes to drop down JComboBoxes. I added that PR in MegaMek/megamek#5369. Once that is merged,  I just need to add the following to CreateCharacterDialog:

```java
@Override
public void optionSwitched(DialogOptionComponent comp, IOption option, int i) {
    refreshXpSpent();
}
```
