### ISSUE TITLE
Mad dog ammo glitch

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#68]
### Environment
v0.3

### Description
just completed mission 7 rescuing Phalen.  one of my mad dogs after being repaired and restocked now looks like this
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/4e091f73-0c82-4333-8359-0b058e5676a7)
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/59eff7ba-33c8-49b9-98ea-9953cca041ec)

### Files

[Young Wolves30580215.cpnx.gz](https://github.com/AaronGullickson/mekhq/files/15048515/Young.Wolves30580215.cpnx.gz)

**Comment by AaronGullickson** [comment]
This is an odd one, but I don't think its specific to story arcs. it might reflect the older nature of the campaign file possibly or could just be a straight up bug. Lets see if others notice once Story Arcs is out in 49.20 and then a proper issue can be filed.
