### ISSUE TITLE
RFE: 'Change Faction' StoryTrigger (Placeholder)

### ISSUE THREAD

**Issue by sldfgunslinger2766** [AaronGullickson/mekhq#69]
While I realize that there will be a limited set of Story Triggers in the initial release, I would like to propose a potential Story Trigger for inclusion later down the line in the development process. Please consider adding a trigger that will change a units Faction within the campaign, either at the completion of a Story Arc or potentially linked to another specified Trigger within the main Arc. Example: A Story Arc begins with the player in command of a small planetary militia in the defense of their Periphery home world. After playing thru a set of scenarios in the arc, at its conclusion, the PC unit leaves the world for the mercenary life.  This trigger would automatically change Campaign Setting/General/Faction from the faction of origin to Mercenary  or another faction specified in the hypothetical ChangeFactionStoryTrigger, thus allowing for a seamless transition to a traditional AtB/Stratcon campaign. Thank you for your time, hard work and consideration!

**Comment by AaronGullickson** [comment]
@sldfgunslinger2766 Could you post this on this issue on the main MHQ issues site? Story arcs was merged yesterday (!) so you can now officially make RFEs about it there. We even have a specific label for Story Arc RFEs.
